Changed the kernel build case without genkerenl to use make olddefconfig instead of silentoldconfig.  olddefconfig won't ask questions - it is ACTUALLY silent.  silentoldconfig is neighter silent nor free of questions and is really equivalent to oldocnfig

diff --git a/gentoo/emerge-sync b/gentoo/emerge-sync
--- a/gentoo/emerge-sync
+++ b/gentoo/emerge-sync
@@ -108,7 +108,7 @@ if [ "$CHECKKERNEL" = "true" ]; then
 			if [ `which genkernel` -a -x `which genkernel` ]; then
 				genkernel --oldconfig --kernel-config=.config all || die "Genkernel failed!"
 			else
-				yes '' | make silentoldconfig || die "Could not automatically update configuration"
+				make olddefconfig || die "Could not automatically update configuration"
 				make modules_prepare || die "Modules_prepare failed with $?"
 				emerge @module-rebuild || die "Modules rebuild failed with $?"
 				make -j5 || die "Build failed with $?"
